version: '3.9'

services:
  fastapi-api:
    build: .
    container_name: financial-notes-api
    ports:
      - "8000:8000"
    volumes:
      - ./input:/app/input
      - ./output1:/app/output1
      - ./generated_notes:/app/generated_notes
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    env_file:
      - .env
    restart: unless-stopped